# Generated by Django 5.0.6 on 2024-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photo_works_alter_service_fourth_paragraph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photos',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
