# Generated by Django 5.0.6 on 2024-06-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gallery_photos_gallery_image_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='category',
            field=models.CharField(default=1, max_length=200, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='first_paragraph',
            field=models.TextField(default=1, verbose_name='Первый параграф'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='fourth_paragraph',
            field=models.TextField(default=1, verbose_name='Четвёртый параграф'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='second_paragraph',
            field=models.TextField(default=1, verbose_name='Второй параграф'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='third_paragraph',
            field=models.TextField(default=1, verbose_name='Третий параграф'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.works', verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author', verbose_name='Автор')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.works', verbose_name='Проект')),
            ],
        ),
    ]
