# Generated by Django 5.0.6 on 2024-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_works_category_works_first_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
    ]
