# Generated by Django 5.0.6 on 2024-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comments_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
