# Generated by Django 5.0.6 on 2024-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='images/default_photo.jpg', upload_to='images/', verbose_name='Фотография'),
        ),
    ]
